import type { Exercise } from '@/types/fitness';

// Generated by scripts/migrate-exercises.ts
export const EXERCISE_DATABASE: Exercise[] = [
  {
    "id": "bench_press",
    "name": "Barbell Bench Press",
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "front_deltoid",
      "triceps"
    ],
    "equipment": [
      "barbell",
      "bench"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Plant feet firmly",
      "Arch upper back slightly",
      "Lower to mid-chest",
      "Drive through legs"
    ],
    "description": "The Barbell Bench Press is the quintessential upper-body pressing exercise, targeting the pectorals, triceps, and anterior deltoids. It allows for maximal loading and is a primary driver for upper body strength and hypertrophy.",
    "steps": [
      "Lie flat on the bench with your eyes directly under the bar.",
      "Grip the bar with hands slightly wider than shoulder-width, wrapping thumbs around the bar.",
      "Plant your feet firmly on the ground and squeeze your shoulder blades together.",
      "Unrack the bar and hold it directly over your shoulders with arms fully extended.",
      "Lower the bar under control to your mid-chest (nipple line), keeping elbows at a 45-degree angle.",
      "Press the bar back up explosively to the starting position, extending arms fully."
    ],
    "variations": [
      {
        "name": "Dumbbell Bench Press",
        "description": "Uses individual weights to increase stabilization demands and even out muscle imbalances.",
        "type": "alternative"
      },
      {
        "name": "Incline Bench Press",
        "description": "Targets the upper chest (clavicular head) more than the flat bench.",
        "type": "alternative"
      },
      {
        "name": "Close-Grip Bench Press",
        "description": "Narrows the grip to place more emphasis on the triceps.",
        "type": "alternative"
      }
    ],
    "category": "strength",
    "difficulty": "Intermediate",
    "metabolic": {
      "met": 5
    }
  },
  {
    "id": "dumbbell_bench_press",
    "name": "Dumbbell Bench Press",
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "front_deltoid",
      "triceps"
    ],
    "equipment": [
      "dumbbells",
      "bench"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Keep elbows at 45°",
      "Touch dumbbells at top",
      "Control the descent"
    ],
    "description": "Standard Dumbbell Bench Press movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "pushup",
    "name": "Push-Up",
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [
      "front_deltoid",
      "triceps",
      "abs"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "contraindications": [
      "wrist_injury"
    ],
    "cues": [
      "Body in straight line",
      "Elbows at 45°",
      "Full range of motion",
      "Don't sag hips"
    ],
    "description": "The Push-Up is a foundational bodyweight exercise that builds strength in the chest, shoulders, and triceps while engaging the core for stability. It requires no equipment and can be modified for all fitness levels.",
    "steps": [
      "Start in a high plank position with hands slightly wider than shoulders.",
      "Engage your core and glutes to keep your body in a straight line from head to heels.",
      "Lower your body until your chest nearly touches the floor, keeping elbows tucked at about 45 degrees.",
      "Push through your hands to return to the starting position."
    ],
    "variations": [
      {
        "name": "Knee Push-Up",
        "description": "Performed on knees to reduce the load, ideal for beginners.",
        "type": "regression"
      },
      {
        "name": "Diamond Push-Up",
        "description": "Hands close together to target the triceps.",
        "type": "progression"
      },
      {
        "name": "Decline Push-Up",
        "description": "Feet elevated on a surface to target the upper chest/shoulders.",
        "type": "progression"
      }
    ],
    "category": "strength",
    "difficulty": "Beginner",
    "metabolic": {
      "met": 3.8
    }
  },
  {
    "id": "incline_dumbbell_press",
    "name": "Incline Dumbbell Press",
    "primaryMuscles": [
      "chest",
      "front_deltoid"
    ],
    "secondaryMuscles": [
      "triceps"
    ],
    "equipment": [
      "dumbbells",
      "bench"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "30-45° incline",
      "Drive through chest",
      "Squeeze at top"
    ],
    "description": "Standard Incline Dumbbell Press movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "cable_fly",
    "name": "Cable Fly",
    "primaryMuscles": [
      "chest"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Slight bend in elbows",
      "Squeeze chest at center",
      "Control the stretch"
    ],
    "description": "Standard Cable Fly movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "barbell_row",
    "name": "Barbell Row",
    "primaryMuscles": [
      "upper_back",
      "lats"
    ],
    "secondaryMuscles": [
      "biceps",
      "rear_deltoid",
      "lower_back"
    ],
    "equipment": [
      "barbell"
    ],
    "patterns": [
      "horizontal_pull"
    ],
    "contraindications": [
      "back_injury",
      "no_heavy_spinal_load"
    ],
    "cues": [
      "Hinge at hips",
      "Pull to lower chest",
      "Squeeze shoulder blades",
      "Back flat always"
    ],
    "description": "The Barbell Row is a compound pulling exercise that builds mass and strength in the upper back, lats, and rear delts. It creates a thick, strong back and improves posture.",
    "steps": [
      "Stand with feet shoulder-width apart, holding the barbell with an overhand grip.",
      "Hinge at your hips, keeping your back straight and knees slightly bent, until your torso is near parallel to the floor.",
      "Let the bar hang with arms fully extended.",
      "Pull the bar towards your lower chest/upper abdomen, driving your elbows up and back.",
      "Squeeze your shoulder blades together at the top.",
      "Lower the bar back to the starting position with control."
    ],
    "variations": [
      {
        "name": "Pendlay Row",
        "description": "Each rep starts from the floor (dead stop) to build explosive power.",
        "type": "alternative"
      },
      {
        "name": "Underhand (Yates) Row",
        "description": "Uses a supinated grip to target the lats and biceps more heavily.",
        "type": "alternative"
      }
    ],
    "category": "strength",
    "difficulty": "Intermediate",
    "metabolic": {
      "met": 5
    }
  },
  {
    "id": "dumbbell_row",
    "name": "Dumbbell Row",
    "primaryMuscles": [
      "upper_back",
      "lats"
    ],
    "secondaryMuscles": [
      "biceps",
      "rear_deltoid"
    ],
    "equipment": [
      "dumbbells",
      "bench"
    ],
    "patterns": [
      "horizontal_pull"
    ],
    "contraindications": [],
    "cues": [
      "Support on bench",
      "Pull to hip",
      "Lead with elbow"
    ],
    "description": "Unilateral rowing for back thickness.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "cable_row",
    "name": "Seated Cable Row",
    "primaryMuscles": [
      "upper_back",
      "lats"
    ],
    "secondaryMuscles": [
      "biceps",
      "rear_deltoid"
    ],
    "equipment": [
      "cables"
    ],
    "patterns": [
      "horizontal_pull"
    ],
    "contraindications": [],
    "cues": [
      "Sit tall",
      "Pull to belly button",
      "Squeeze back at end"
    ],
    "description": "Standard Seated Cable Row movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "inverted_row",
    "name": "Inverted Row",
    "primaryMuscles": [
      "upper_back",
      "lats"
    ],
    "secondaryMuscles": [
      "biceps",
      "rear_deltoid",
      "abs"
    ],
    "equipment": [
      "bodyweight",
      "pullup_bar"
    ],
    "patterns": [
      "horizontal_pull"
    ],
    "contraindications": [],
    "cues": [
      "Body straight",
      "Pull chest to bar",
      "Control descent"
    ],
    "description": "Standard Inverted Row movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "pullup",
    "name": "Pull-Up",
    "primaryMuscles": [
      "lats",
      "upper_back"
    ],
    "secondaryMuscles": [
      "biceps",
      "forearms"
    ],
    "equipment": [
      "pullup_bar",
      "bodyweight"
    ],
    "patterns": [
      "vertical_pull"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Dead hang start",
      "Pull elbows down",
      "Chin over bar",
      "Control the descent"
    ],
    "description": "The Pull-Up is the ultimate test of upper-body pulling strength. It targets the latissimus dorsi (back width) and biceps, building a V-taper physique.",
    "steps": [
      "Grab the bar with an overhand grip slightly wider than your shoulders.",
      "Hang freely with arms fully extended (dead hang).",
      "Pull your chest up toward the bar by driving your elbows down and back.",
      "Continue pulling until your chin passes the bar.",
      "Lower yourself back to the dead hang position with control."
    ],
    "variations": [
      {
        "name": "Chin-Up",
        "description": "Underhand grip to target biceps more.",
        "type": "alternative"
      },
      {
        "name": "Assisted Pull-Up",
        "description": "Use a machine or band to reduce bodyweight load.",
        "type": "regression"
      },
      {
        "name": "Weighted Pull-Up",
        "description": "Add a weight belt or vest for increased difficulty.",
        "type": "progression"
      }
    ],
    "category": "strength",
    "difficulty": "Intermediate",
    "metabolic": {
      "met": 8
    }
  },
  {
    "id": "lat_pulldown",
    "name": "Lat Pulldown",
    "primaryMuscles": [
      "lats"
    ],
    "secondaryMuscles": [
      "upper_back",
      "biceps"
    ],
    "equipment": [
      "cables",
      "machines"
    ],
    "patterns": [
      "vertical_pull"
    ],
    "contraindications": [],
    "cues": [
      "Lean back slightly",
      "Pull to upper chest",
      "Squeeze lats"
    ],
    "description": "Vertical pull machine for back width.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "chinup",
    "name": "Chin-Up",
    "primaryMuscles": [
      "lats",
      "biceps"
    ],
    "secondaryMuscles": [
      "upper_back",
      "forearms"
    ],
    "equipment": [
      "pullup_bar",
      "bodyweight"
    ],
    "patterns": [
      "vertical_pull"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Underhand grip",
      "Pull chin over bar",
      "Control down"
    ],
    "description": "Standard Chin-Up movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "overhead_press",
    "name": "Overhead Press",
    "primaryMuscles": [
      "front_deltoid",
      "side_deltoid"
    ],
    "secondaryMuscles": [
      "triceps",
      "upper_back"
    ],
    "equipment": [
      "barbell",
      "squat_rack"
    ],
    "patterns": [
      "vertical_push"
    ],
    "contraindications": [
      "no_overhead",
      "shoulder_injury"
    ],
    "cues": [
      "Brace core",
      "Press straight up",
      "Lockout overhead"
    ],
    "description": "Standing barbell press for shoulder strength.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "dumbbell_shoulder_press",
    "name": "Dumbbell Shoulder Press",
    "primaryMuscles": [
      "front_deltoid",
      "side_deltoid"
    ],
    "secondaryMuscles": [
      "triceps"
    ],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [
      "vertical_push"
    ],
    "contraindications": [
      "no_overhead",
      "shoulder_injury"
    ],
    "cues": [
      "Seated or standing",
      "Press up and slightly in",
      "Control down"
    ],
    "description": "Standard Dumbbell Shoulder Press movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "pike_pushup",
    "name": "Pike Push-Up",
    "primaryMuscles": [
      "front_deltoid"
    ],
    "secondaryMuscles": [
      "triceps",
      "upper_back"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "vertical_push"
    ],
    "contraindications": [
      "no_overhead",
      "wrist_injury"
    ],
    "cues": [
      "Hips high",
      "Head between arms",
      "Touch floor with head"
    ],
    "description": "Standard Pike Push-Up movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "lateral_raise",
    "name": "Lateral Raise",
    "primaryMuscles": [
      "side_deltoid"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Slight bend in elbows",
      "Raise to shoulder height",
      "Control down"
    ],
    "description": "Isolation movement for the side delts to build width.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "face_pull",
    "name": "Face Pull",
    "primaryMuscles": [
      "rear_deltoid",
      "upper_back"
    ],
    "secondaryMuscles": [
      "traps"
    ],
    "equipment": [
      "cables"
    ],
    "patterns": [
      "horizontal_pull"
    ],
    "contraindications": [],
    "cues": [
      "Pull to face",
      "Externally rotate at end",
      "Squeeze rear delts"
    ],
    "description": "Standard Face Pull movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "barbell_squat",
    "name": "Barbell Back Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "abs"
    ],
    "equipment": [
      "barbell",
      "squat_rack"
    ],
    "patterns": [
      "squat"
    ],
    "contraindications": [
      "knee_injury",
      "back_injury",
      "no_heavy_spinal_load"
    ],
    "cues": [
      "Brace core",
      "Knees track toes",
      "Depth to parallel or below",
      "Chest up"
    ],
    "description": "The Barbell Back Squat is broadly considered the king of all exercises. It is a full-body compound movement that primarily strengthens the legs and hips but also challenges the core and upper back.",
    "steps": [
      "Place the barbell across your upper back (traps), holding it firmly.",
      "Unrack the bar and take a step back, standing with feet shoulder-width apart.",
      "Inhale deeply and brace your core.",
      "Initiate the movement by pushing your hips back and bending your knees.",
      "Lower your body until your thighs are at least parallel to the floor.",
      "Drive through your feet to stand back up to the starting position."
    ],
    "variations": [
      {
        "name": "Front Squat",
        "description": "Bar is held on the front delts, emphasizing quads and upper back.",
        "type": "alternative"
      },
      {
        "name": "Goblet Squat",
        "description": "Easier to learn, great for beginners.",
        "type": "regression"
      },
      {
        "name": "Pause Squat",
        "description": "Pause at the bottom to build power out of the hole.",
        "type": "progression"
      }
    ],
    "category": "strength",
    "difficulty": "Intermediate",
    "metabolic": {
      "met": 6
    }
  },
  {
    "id": "goblet_squat",
    "name": "Goblet Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "abs"
    ],
    "equipment": [
      "dumbbells",
      "kettlebells"
    ],
    "patterns": [
      "squat"
    ],
    "contraindications": [
      "knee_injury"
    ],
    "cues": [
      "Hold weight at chest",
      "Elbows inside knees",
      "Sit between heels"
    ],
    "description": "Squat holding dumbbell at chest, great for beginners.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "leg_press",
    "name": "Leg Press",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "machines"
    ],
    "patterns": [
      "squat"
    ],
    "contraindications": [],
    "cues": [
      "Feet shoulder width",
      "Full depth without butt lift",
      "Control eccentric"
    ],
    "description": "Machine-based heavy leg builder.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "bodyweight_squat",
    "name": "Bodyweight Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "abs"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "squat"
    ],
    "contraindications": [
      "knee_injury"
    ],
    "cues": [
      "Arms forward for balance",
      "Sit back",
      "Full depth"
    ],
    "description": "Standard Bodyweight Squat movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "deadlift",
    "name": "Conventional Deadlift",
    "primaryMuscles": [
      "hamstrings",
      "glutes",
      "lower_back"
    ],
    "secondaryMuscles": [
      "quads",
      "traps",
      "forearms"
    ],
    "equipment": [
      "barbell"
    ],
    "patterns": [
      "hinge"
    ],
    "contraindications": [
      "back_injury",
      "no_heavy_spinal_load"
    ],
    "cues": [
      "Bar over mid-foot",
      "Chest up",
      "Push floor away",
      "Slack out of bar"
    ],
    "description": "The Conventional Deadlift is a total-body strength builder focusing on the posterior chain. It teaches how to lift heavy objects safely from the ground.",
    "steps": [
      "Stand with feet hip-width apart, with the barbell over your mid-foot.",
      "Bend at the hips to grip the bar just outside your knees.",
      "Drop your hips until your shins touch the bar, keeping your chest up and back flat.",
      "Pull the 'slack' out of the bar, then drive your feet into the floor to lift the weight.",
      "Stand tall, squeezing your glutes at the top.",
      "Return the weight to the floor by hinging at the hips."
    ],
    "variations": [
      {
        "name": "Romanian Deadlift",
        "description": "Starts from the top, focuses on the eccentric (lowering) phase.",
        "type": "alternative"
      },
      {
        "name": "Sumo Deadlift",
        "description": "Wider stance, more quad/glute focus, less lower back strain.",
        "type": "alternative"
      }
    ],
    "category": "strength",
    "difficulty": "Advanced",
    "metabolic": {
      "met": 6
    }
  },
  {
    "id": "romanian_deadlift",
    "name": "Romanian Deadlift",
    "primaryMuscles": [
      "hamstrings",
      "glutes"
    ],
    "secondaryMuscles": [
      "lower_back"
    ],
    "equipment": [
      "barbell",
      "dumbbells"
    ],
    "patterns": [
      "hinge"
    ],
    "contraindications": [
      "back_injury"
    ],
    "cues": [
      "Slight knee bend",
      "Push hips back",
      "Feel hamstring stretch"
    ],
    "description": "Hip hinge focusing on hamstring stretch.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "kettlebell_swing",
    "name": "Kettlebell Swing",
    "primaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "secondaryMuscles": [
      "lower_back",
      "abs"
    ],
    "equipment": [
      "kettlebells"
    ],
    "patterns": [
      "hinge"
    ],
    "contraindications": [
      "back_injury",
      "no_impact"
    ],
    "cues": [
      "Hinge not squat",
      "Snap hips forward",
      "Arms are pendulum"
    ],
    "description": "Standard Kettlebell Swing movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "hip_thrust",
    "name": "Hip Thrust",
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "barbell",
      "bench"
    ],
    "patterns": [
      "hinge"
    ],
    "contraindications": [],
    "cues": [
      "Shoulders on bench",
      "Drive through heels",
      "Squeeze at top"
    ],
    "description": "Loaded glute bridge for maximum glute hypertrophy.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "glute_bridge",
    "name": "Glute Bridge",
    "primaryMuscles": [
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "hinge"
    ],
    "contraindications": [],
    "cues": [
      "Feet flat, knees bent",
      "Squeeze glutes at top",
      "Hold briefly"
    ],
    "description": "Bodyweight hip extension from floor.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "walking_lunge",
    "name": "Walking Lunge",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "bodyweight",
      "dumbbells"
    ],
    "patterns": [
      "lunge"
    ],
    "contraindications": [
      "knee_injury",
      "no_impact"
    ],
    "cues": [
      "Long stride",
      "Front knee over ankle",
      "Push through front heel"
    ],
    "description": "Standard Walking Lunge movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "split_squat",
    "name": "Split Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "bodyweight",
      "dumbbells"
    ],
    "patterns": [
      "lunge"
    ],
    "contraindications": [
      "knee_injury"
    ],
    "cues": [
      "Stationary stance",
      "Drop back knee",
      "Stay upright"
    ],
    "description": "Standard Split Squat movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "bulgarian_split_squat",
    "name": "Bulgarian Split Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "hamstrings"
    ],
    "equipment": [
      "dumbbells",
      "bench",
      "bodyweight"
    ],
    "patterns": [
      "lunge"
    ],
    "contraindications": [
      "knee_injury"
    ],
    "cues": [
      "Rear foot elevated",
      "Lean slightly forward",
      "Drive through front heel"
    ],
    "description": "Unilateral leg exercise for balance and hypertrophy.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "step_up",
    "name": "Step-Up",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bench",
      "dumbbells",
      "bodyweight"
    ],
    "patterns": [
      "lunge"
    ],
    "contraindications": [
      "knee_injury",
      "no_impact"
    ],
    "cues": [
      "Full foot on box",
      "Push through working leg only",
      "Control down"
    ],
    "description": "Standard Step-Up movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "barbell_curl",
    "name": "Barbell Curl",
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ],
    "equipment": [
      "barbell"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "wrist_injury"
    ],
    "cues": [
      "Elbows pinned to sides",
      "Full contraction at top",
      "Control down"
    ],
    "description": "Standard Barbell Curl movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "dumbbell_curl",
    "name": "Dumbbell Curl",
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [
      "forearms"
    ],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Supinate at top",
      "No swinging",
      "Full stretch at bottom"
    ],
    "description": "Standard Dumbbell Curl movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "hammer_curl",
    "name": "Hammer Curl",
    "primaryMuscles": [
      "biceps",
      "forearms"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Neutral grip",
      "Elbows stationary",
      "Squeeze at top"
    ],
    "description": "Neutral grip curl targeting brachialis.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "tricep_pushdown",
    "name": "Tricep Pushdown",
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Elbows locked at sides",
      "Full extension",
      "Control up"
    ],
    "description": "Standard Tricep Pushdown movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "skull_crusher",
    "name": "Skull Crusher",
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell",
      "dumbbells",
      "bench"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "wrist_injury"
    ],
    "cues": [
      "Lower to forehead",
      "Elbows fixed",
      "Full extension"
    ],
    "description": "Standard Skull Crusher movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "dips",
    "name": "Tricep Dips",
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [
      "chest",
      "front_deltoid"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "vertical_push"
    ],
    "contraindications": [
      "shoulder_injury"
    ],
    "cues": [
      "Stay upright for triceps",
      "Full lockout",
      "Control descent"
    ],
    "description": "Bodyweight pushing exercise for chest and triceps.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "overhead_tricep_extension",
    "name": "Overhead Tricep Extension",
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells",
      "cables"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "no_overhead",
      "shoulder_injury"
    ],
    "cues": [
      "Elbows by ears",
      "Full stretch at bottom",
      "Squeeze at top"
    ],
    "description": "Standard Overhead Tricep Extension movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "plank",
    "name": "Plank",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [
      "obliques"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Straight line from head to heels",
      "Brace core",
      "Breathe steadily"
    ],
    "description": "Standard Plank movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "crunch",
    "name": "Crunch",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "back_injury"
    ],
    "cues": [
      "Curl shoulders up",
      "Don't pull neck",
      "Exhale on way up"
    ],
    "description": "Standard Crunch movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "russian_twist",
    "name": "Russian Twist",
    "primaryMuscles": [
      "obliques"
    ],
    "secondaryMuscles": [
      "abs"
    ],
    "equipment": [
      "bodyweight",
      "dumbbells"
    ],
    "patterns": [
      "rotation"
    ],
    "contraindications": [
      "back_injury",
      "no_rotation"
    ],
    "cues": [
      "Lean back slightly",
      "Rotate from core",
      "Touch floor each side"
    ],
    "description": "Rotational core exercise sitting on floor.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner"
  },
  {
    "id": "leg_raise",
    "name": "Leg Raise",
    "primaryMuscles": [
      "abs",
      "hip_flexors"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight",
      "pullup_bar"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [
      "back_injury"
    ],
    "cues": [
      "Keep legs straight",
      "Control the descent",
      "Don't swing"
    ],
    "description": "Standard Leg Raise movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "dead_bug",
    "name": "Dead Bug",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [
      "hip_flexors"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Back flat on floor",
      "Opposite arm and leg extend",
      "Breathe throughout"
    ],
    "description": "Core stability exercise moving opposite limbs while keeping spine flat.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner"
  },
  {
    "id": "calf_raise",
    "name": "Standing Calf Raise",
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight",
      "dumbbells",
      "machines"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Full stretch at bottom",
      "Rise onto toes",
      "Pause at top"
    ],
    "description": "Isolation for the gastrocnemius muscle.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner"
  },
  {
    "id": "seated_calf_raise",
    "name": "Seated Calf Raise",
    "primaryMuscles": [
      "calves"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "machines",
      "dumbbells"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Knees at 90°",
      "Full range of motion",
      "Slow negatives"
    ],
    "description": "Standard Seated Calf Raise movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "farmers_carry",
    "name": "Farmer's Carry",
    "primaryMuscles": [
      "forearms",
      "traps"
    ],
    "secondaryMuscles": [
      "abs",
      "obliques"
    ],
    "equipment": [
      "dumbbells",
      "kettlebells"
    ],
    "patterns": [
      "carry"
    ],
    "contraindications": [],
    "cues": [
      "Stand tall",
      "Shoulders back",
      "Walk with control"
    ],
    "description": "Standard Farmer's Carry movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "shrug",
    "name": "Dumbbell Shrug",
    "primaryMuscles": [
      "traps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells",
      "barbell"
    ],
    "patterns": [
      "isolation"
    ],
    "contraindications": [],
    "cues": [
      "Lift shoulders straight up",
      "Don't roll",
      "Pause at top"
    ],
    "description": "Standard Dumbbell Shrug movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "single_leg_squat",
    "name": "Single-Leg Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "abs",
      "calves"
    ],
    "equipment": [
      "bodyweight",
      "dumbbells"
    ],
    "patterns": [
      "squat"
    ],
    "stabilityLevel": "unstable",
    "type": "strength",
    "contraindications": [
      "knee_injury",
      "balance_issues"
    ],
    "cues": [
      "Balance on one leg",
      "Sit back",
      "Keep knee aligned"
    ],
    "description": "Standard Single-Leg Squat movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "stability_ball_pushup",
    "name": "Stability Ball Push-Up",
    "primaryMuscles": [
      "chest",
      "triceps"
    ],
    "secondaryMuscles": [
      "abs",
      "front_deltoid"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "stabilityLevel": "unstable",
    "type": "strength",
    "contraindications": [
      "wrist_injury"
    ],
    "cues": [
      "Hands on ball",
      "Stabilize core",
      "Control descent"
    ],
    "description": "Standard Stability Ball Push-Up movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "single_leg_rdl",
    "name": "Single-Leg RDL",
    "primaryMuscles": [
      "hamstrings",
      "glutes"
    ],
    "secondaryMuscles": [
      "calves",
      "lower_back"
    ],
    "equipment": [
      "dumbbells",
      "kettlebells",
      "bodyweight"
    ],
    "patterns": [
      "hinge"
    ],
    "stabilityLevel": "unstable",
    "type": "strength",
    "contraindications": [
      "back_injury"
    ],
    "cues": [
      "Hinge at hips",
      "Keep back flat",
      "Floating leg stays straight"
    ],
    "description": "Unilateral hinge for balance and hamstring strength.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate"
  },
  {
    "id": "stability_ball_plank",
    "name": "Stability Ball Plank",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [
      "front_deltoid"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "isolation"
    ],
    "stabilityLevel": "unstable",
    "type": "strength",
    "contraindications": [],
    "cues": [
      "Elbows on ball",
      "Circular motions",
      "Brace hard"
    ],
    "description": "Standard Stability Ball Plank movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "squat_jump",
    "name": "Squat Jump",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [
      "calves"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "squat"
    ],
    "stabilityLevel": "stable",
    "type": "plyometric",
    "contraindications": [
      "knee_injury",
      "no_impact",
      "no_jumping"
    ],
    "cues": [
      "Explode up",
      "Soft landing",
      "Reset between reps"
    ],
    "description": "Standard Squat Jump movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "plyo_pushup",
    "name": "Plyometric Push-Up",
    "primaryMuscles": [
      "chest",
      "triceps"
    ],
    "secondaryMuscles": [
      "front_deltoid"
    ],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "stabilityLevel": "stable",
    "type": "plyometric",
    "contraindications": [
      "wrist_injury",
      "no_impact"
    ],
    "cues": [
      "Explode off ground",
      "Clap if possible",
      "Absorb impact"
    ],
    "description": "Standard Plyometric Push-Up movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "medicine_ball_chest_pass",
    "name": "Medicine Ball Chest Pass",
    "primaryMuscles": [
      "chest",
      "triceps"
    ],
    "secondaryMuscles": [
      "abs"
    ],
    "equipment": [
      "medicine_ball",
      "bodyweight"
    ],
    "patterns": [
      "horizontal_push"
    ],
    "stabilityLevel": "stable",
    "type": "power",
    "contraindications": [],
    "cues": [
      "Explosive push",
      "Full extension",
      "Step into it"
    ],
    "description": "Standard Medicine Ball Chest Pass movement.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate"
  },
  {
    "id": "box_jump",
    "name": "Box Jump",
    "primaryMuscles": [
      "quads",
      "glutes",
      "calves"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [
      "squat"
    ],
    "stabilityLevel": "stable",
    "type": "plyometric",
    "contraindications": [
      "knee_injury",
      "no_impact",
      "no_jumping"
    ],
    "cues": [
      "Land soft",
      "Stand tall at top",
      "Step down"
    ],
    "description": "Standard Box Jump movement.",
    "steps": [],
    "variations": [],
    "category": "plyometric",
    "difficulty": "Intermediate"
  },
  {
    "id": "stomach_vacuum",
    "name": "Stomach Vacuum",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Isometric contraction of the Transverse Abdominis to tighten the waist.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "bird_dog",
    "name": "Bird Dog",
    "primaryMuscles": [
      "lower_back",
      "abs",
      "glutes"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Spinal stability movement extending opposite arm and leg.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "hollow_body_hold",
    "name": "Hollow Body Hold",
    "primaryMuscles": [
      "abs",
      "hip_flexors"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Gymnastic core hold creating a 'dish' shape.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "pallof_press",
    "name": "Pallof Press",
    "primaryMuscles": [
      "obliques",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables",
      "band"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Anti-rotation hold resisting sideways cable tension.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "rkc_plank",
    "name": "RKC Plank",
    "primaryMuscles": [
      "abs",
      "glutes",
      "quads"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "High-tension plank maximizing full body contraction.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "swiss_ball_stir_pot",
    "name": "Swiss Ball Stir the Pot",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "stability_ball"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Dynamic plank rolling elbows in circles on a stability ball.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "jefferson_curl",
    "name": "Jefferson Curl",
    "primaryMuscles": [
      "lower_back",
      "hamstrings"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell",
      "kettlebells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Segmental spinal flexion and extension with weight.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "cat_cow",
    "name": "Cat-Cow",
    "primaryMuscles": [
      "lower_back"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Gentle spinal mobility flow.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "push_up",
    "name": "Push-Up",
    "primaryMuscles": [
      "chest",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Classic bodyweight chest and tricep builder.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "skullcrushers",
    "name": "Skullcrushers",
    "primaryMuscles": [
      "triceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "ez_bar",
      "dumbbells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Tricep isolation exercise lying on a bench.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "pull_up",
    "name": "Pull-Up",
    "primaryMuscles": [
      "lats"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "pullup_bar"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Vertical pulling exercise for back width.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "squat",
    "name": "Barbell Back Squat",
    "primaryMuscles": [
      "quads",
      "glutes"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell",
      "squat_rack"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "The king of lower body exercises.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "cable_crunch",
    "name": "Cable Crunch",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Weighted abdominal flexion using a high cable.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "farmers_walk",
    "name": "Farmer's Walk",
    "primaryMuscles": [
      "abs",
      "traps",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Walking with heavy weights for grip and core.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "face_pulls",
    "name": "Face Pulls",
    "primaryMuscles": [
      "rear_deltoid",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Rear delt and rotator cuff exercise for posture.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "incline_bench",
    "name": "Incline Bench Press",
    "primaryMuscles": [
      "abs",
      "front_deltoid"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell",
      "bench"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Pressing movement targeting the upper chest.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "bicep_curl",
    "name": "Barbell Bicep Curl",
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Classic bicep mass builder.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "leg_curl",
    "name": "Lying Leg Curl",
    "primaryMuscles": [
      "hamstrings"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "machines"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Hamstring isolation machine.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "hanging_leg_raise",
    "name": "Hanging Leg Raise",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "pullup_bar"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Advanced core flexion hanging from a bar.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "ab_wheel",
    "name": "Ab Wheel Rollout",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "ab_wheel"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Anti-extension core rollout.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "bicycle_crunch",
    "name": "Bicycle Crunch",
    "primaryMuscles": [
      "abs",
      "obliques"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Dynamic core exercise hitting abs and obliques.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "med_ball_slam",
    "name": "Med Ball Slam",
    "primaryMuscles": [
      "abs",
      "lats"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "medicine_ball"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Explosive full body slam for power.",
    "steps": [],
    "variations": [],
    "category": "plyometric",
    "difficulty": "Beginner",
    "type": "plyometric"
  },
  {
    "id": "plyo_push_up",
    "name": "Plyometric Push-Up",
    "primaryMuscles": [
      "chest",
      "triceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Explosive push-up leaving the ground.",
    "steps": [],
    "variations": [],
    "category": "plyometric",
    "difficulty": "Advanced",
    "type": "plyometric"
  },
  {
    "id": "serratus_punch",
    "name": "Serratus Punch",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells",
      "band"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Scapular protraction exercise.",
    "steps": [],
    "variations": [],
    "category": "other",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "tibialis_raise",
    "name": "Tibialis Raise",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "wall",
      "tib_bar"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Shin muscle exercise for knee health.",
    "steps": [],
    "variations": [],
    "category": "other",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "farmers_walk_heavy",
    "name": "Heavy Farmer's Walk",
    "primaryMuscles": [
      "traps",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Walking with heavy weights for strongman conditioning.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "sled_push",
    "name": "Sled Push",
    "primaryMuscles": [
      "quads",
      "glutes",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "sled"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Conditioning exercise pushing a weighted sled.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "planche",
    "name": "Planche",
    "primaryMuscles": [
      "abs",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "floor"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Static hold with body parallel to ground.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Elite",
    "type": "strength"
  },
  {
    "id": "muscle_up",
    "name": "Muscle Up",
    "primaryMuscles": [
      "lats",
      "triceps",
      "chest"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "pullup_bar",
      "rings"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Explosive pull-up transitioning into a dip.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "landmine_press",
    "name": "Landmine Press",
    "primaryMuscles": [
      "abs",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "landmine"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Unilateral shoulder press with leverage.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "renegade_row",
    "name": "Renegade Row",
    "primaryMuscles": [
      "abs",
      "lats"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Plank row hybrid for anti-rotation core strength.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "beast_crawl",
    "name": "Beast Crawl",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Quadrupedal movement pattern.",
    "steps": [],
    "variations": [],
    "category": "other",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "running",
    "name": "Running",
    "primaryMuscles": [
      "abs",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Fundamental human locomotion.",
    "steps": [],
    "variations": [],
    "category": "cardio",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "yoga",
    "name": "Yoga",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "mat"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Mind-body practice for flexibility.",
    "steps": [],
    "variations": [],
    "category": "flexibility",
    "difficulty": "All Levels",
    "type": "strength"
  },
  {
    "id": "foam_rolling",
    "name": "Foam Rolling",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "foam_roller"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Self-myofascial release technique.",
    "steps": [],
    "variations": [],
    "category": "flexibility",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "clamshells",
    "name": "Clamshells",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "band"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Glute medius isolation for hip stability.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "banded_lateral_walk",
    "name": "Banded Lateral Walk",
    "primaryMuscles": [
      "glutes",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "mini_band"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Walking sideways with band tension for hips.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "decline_bench",
    "name": "Decline Bench Press",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell",
      "bench"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Bench press with feet elevated targeting lower chest.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "frontal_raise",
    "name": "Front Raise",
    "primaryMuscles": [
      "front_deltoid"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "dumbbells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Anterior deltoid isolation.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "seated_cable_row",
    "name": "Seated Cable Row",
    "primaryMuscles": [
      "lats",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Horizontal row for mid-back thickness.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "preacher_curl",
    "name": "Preacher Curl",
    "primaryMuscles": [
      "biceps"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "ez_bar",
      "bench"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Bicep isolation removing momentum.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "front_squat",
    "name": "Front Squat",
    "primaryMuscles": [
      "quads",
      "upper_back"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "barbell"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Squat with bar on front delts, targeting quads and core.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "woodchopper",
    "name": "Cable Woodchopper",
    "primaryMuscles": [
      "obliques"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "cables"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Rotational power movement across the body.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "depth_jump",
    "name": "Depth Jump",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "box"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Stepping off box and immediately jumping up.",
    "steps": [],
    "variations": [],
    "category": "plyometric",
    "difficulty": "Advanced",
    "type": "plyometric"
  },
  {
    "id": "neck_flexion",
    "name": "Neck Flexion",
    "primaryMuscles": [
      "neck"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "plate"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Strengthening the front neck muscles.",
    "steps": [],
    "variations": [],
    "category": "other",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "sandbag_load",
    "name": "Sandbag Load",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "sandbag"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Lifting unstable object to a platform.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "atlas_stone",
    "name": "Atlas Stone Lift",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "stone"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Lifting a concrete stone to a platform.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "front_lever",
    "name": "Front Lever",
    "primaryMuscles": [
      "lats",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "pullup_bar"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Static hold hanging horizontally from bar.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Elite",
    "type": "strength"
  },
  {
    "id": "human_flag",
    "name": "Human Flag",
    "primaryMuscles": [
      "obliques",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "pole"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Sideways static hold on a vertical pole.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Elite",
    "type": "strength"
  },
  {
    "id": "turkish_get_up",
    "name": "Turkish Get-Up",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "kettlebells"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Standing up from floor with weight held overhead.",
    "steps": [],
    "variations": [],
    "category": "core",
    "difficulty": "Advanced",
    "type": "strength"
  },
  {
    "id": "cossack_squat",
    "name": "Cossack Squat",
    "primaryMuscles": [
      "adductors",
      "quads"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Side-to-side deep squat for mobility and strength.",
    "steps": [],
    "variations": [],
    "category": "strength",
    "difficulty": "Intermediate",
    "type": "strength"
  },
  {
    "id": "crab_walk",
    "name": "Crab Walk",
    "primaryMuscles": [
      "triceps",
      "glutes"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Walking on hands and feet in reverse bridge.",
    "steps": [],
    "variations": [],
    "category": "other",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "jump_rope",
    "name": "Jump Rope",
    "primaryMuscles": [
      "calves",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "rope"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Bouncing conditioning for calves and coordination.",
    "steps": [],
    "variations": [],
    "category": "cardio",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "rowing",
    "name": "Rowing",
    "primaryMuscles": [
      "abs",
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "machines"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Full body cardio pulling movement.",
    "steps": [],
    "variations": [],
    "category": "cardio",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "dynamic_stretching",
    "name": "Dynamic Stretching",
    "primaryMuscles": [
      "abs"
    ],
    "secondaryMuscles": [],
    "equipment": [
      "bodyweight"
    ],
    "patterns": [],
    "contraindications": [],
    "cues": [],
    "description": "Moving through range of motion to warm up.",
    "steps": [],
    "variations": [],
    "category": "flexibility",
    "difficulty": "Beginner",
    "type": "strength"
  },
  {
    "id": "russian_twist",
    "name": "Russian Twist",
    "primaryMuscles": ["obliques", "abs"],
    "secondaryMuscles": ["hip_flexors", "upper_back", "lower_back"],
    "equipment": ["bodyweight"],
    "patterns": ["rotation"],
    "contraindications": ["back_injury", "neck_injury", "pregnancy"],
    "cues": [
      "V-shape torso",
      "Twist from core",
      "Follow hands with eyes",
      "Straight spine"
    ],
    "description": "The Russian twist is a great exercise to build core and shoulder strength. Athletes use it for rotational movement, which can be seen in sports. Though it seems easy, it takes a lot of effort and stability.",
    "steps": [
      "Root into your sit bones as you lift your feet from the floor, keeping your knees bent.",
      "Elongate and straighten your spine at a 45-degree angle from the floor, creating a V shape with your torso and thighs.",
      "Reach your arms straight out in front, interlacing your fingers or clasping your hands together.",
      "Use your abdominals to twist to the right, then back to center, and then to the left."
    ],
    "variations": [
      {
        "name": "Weighted Twist",
        "description": "Hold a weight (dumbbell/medicine ball) at chest level while twisting.",
        "type": "progression"
      },
      {
        "name": "Leg-cross Twists",
        "description": "Cross one calf over the other as you twist to that side.",
        "type": "alternative"
      },
      {
        "name": "Punch Twists",
        "description": "Punch across your body instead of just twisting clasped hands.",
        "type": "alternative"
      },
      {
        "name": "Decline Twists",
        "description": "Perform the movement on a decline bench.",
        "type": "progression"
      }
    ],
    "category": "core",
    "difficulty": "Intermediate"
  },
  {
    "id": "side_plank",
    "name": "Side Plank",
    "primaryMuscles": ["obliques", "abs"],
    "secondaryMuscles": ["side_deltoid", "front_deltoid"],
    "equipment": ["bodyweight", "mat"],
    "patterns": ["isolation"],
    "contraindications": ["shoulder_injury"],
    "cues": [
      "Straight line head to feet",
      "Hips lifted high",
      "Elbow under shoulder"
    ],
    "description": "A static hold that builds lateral core stability and shoulder strength.",
    "steps": [
      "Lie on your left side with your feet stacked or with one foot in front of the other.",
      "Place your left forearm on the floor and lift your hips off the ground.",
      "Keep your hips lifted to form a straight line from the feet to the head.",
      "Hold this position for time."
    ],
    "variations": [
      {
        "name": "Knee Side Plank",
        "description": "Perform with bottom knee on the ground.",
        "type": "regression"
      },
      {
        "name": "Side Plank Dips",
        "description": "Lower and lift hips while in position.",
        "type": "progression"
      }
    ],
    "category": "core",
    "difficulty": "Beginner"
  },
  {
    "id": "heel_touches",
    "name": "Heel Touches",
    "primaryMuscles": ["obliques", "abs"],
    "secondaryMuscles": [],
    "equipment": ["bodyweight", "mat"],
    "patterns": ["isolation"],
    "contraindications": ["neck_injury"],
    "cues": [
      "Head/shoulders slightly up",
      "Reach for heels",
      "Squeeze side abs"
    ],
    "description": "A lying core exercise that targets the obliques through lateral flexion.",
    "steps": [
      "Lie on your back with knees bent and feet on the floor near hips.",
      "Lift head and upper body slightly.",
      "Reach right arm forward toward right toes.",
      "Return to center and reach left arm to left toes."
    ],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner"
  },
  {
    "id": "plank_twists",
    "name": "Forearm Plank Twists",
    "primaryMuscles": ["abs", "obliques"],
    "secondaryMuscles": ["side_deltoid", "front_deltoid"],
    "equipment": ["bodyweight", "mat"],
    "patterns": ["rotation"],
    "contraindications": ["back_injury"],
    "cues": [
      "Maintain plank form",
      "Rotate hips side to side",
      "Control the tap"
    ],
    "description": "Dynamic plank variation adding rotation to target the obliques.",
    "steps": [
      "Start in a forearm plank position.",
      "Rotate and drop your hips over to the right side.",
      "Gently tap the floor with your hip before returning to center.",
      "Repeat on the left side."
    ],
    "variations": [],
    "category": "core",
    "difficulty": "Intermediate"
  },
  {
    "id": "bird_dog",
    "name": "Bird Dog",
    "primaryMuscles": ["lower_back", "glutes", "abs"],
    "secondaryMuscles": ["front_deltoid", "lower_back"],
    "equipment": ["bodyweight", "mat"],
    "patterns": ["isolation"],
    "contraindications": [],
    "cues": [
      "Tabletop position",
      "Opposite arm/leg extend",
      "Flat back",
      "Squeeze glute"
    ],
    "description": "A stability exercise that strengthens the core, lower back, and improves balance.",
    "steps": [
      "Begin from a tabletop position.",
      "Engage your core as you extend your left arm and right leg.",
      "Hold for a few seconds, keeping shoulders and hips square.",
      "Return to start and switch sides."
    ],
    "variations": [],
    "category": "core",
    "difficulty": "Beginner"
  }
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_DATABASE.find(e => e.id === id);
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISE_DATABASE.filter(e =>
    e.primaryMuscles.includes(muscle as any) || e.secondaryMuscles.includes(muscle as any)
  );
}

export function getExercisesByEquipment(equipment: string[]): Exercise[] {
  return EXERCISE_DATABASE.filter(e =>
    e.equipment.some(eq => equipment.includes(eq))
  );
}

export function getExercisesByPattern(pattern: string): Exercise[] {
  return EXERCISE_DATABASE.filter(e => e.patterns.includes(pattern as any));
}
